myproject/myapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, external, userRegistration, userLogin, userLogout, update

urlpatterns = [
    path('', home, name='home'),
    path('update', update, name='update'),
    path('ext', external, name='external'),
    path('registration', userRegistration, name='registration'),
    path('login', userLogin, name='login'),
    path('logout', userLogout, name='logout')
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from myapp.views import profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls'))
]

if settings.DEBUG == True:
    # serve the media files during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/myapp/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# inherit user built-in model here
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pics/default.jpeg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

# Create Signals to Automatically Create/Update Profile
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

# Create your models here.
class Msg(models.Model):
    id = models.AutoField(db_index=True, primary_key=True)
    # sender = models.CharField(max_length=255)
    msg = models.TextField(default='')
    senton = models.DateTimeField(default=datetime.now())  # automatically set to current date and time when the object is created
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_DEFAULT, default=1)
    # user = models.ManyToOneRel(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.username

myproject/myapp/forms.py
from django import forms
from .models import Profile, Msg
from django.contrib.auth.models import User
# from .models import Msg

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

class MsgForm(forms.ModelForm):
    msg = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'msgArea'}))

    class Meta:
       model = Msg
       fields = ['msg']
       labels = {'msg':'Message'}


       

myproject/myapp/views.py
from django.shortcuts import render, redirect
from .models import Msg 
from .forms import MsgForm, ProfileUpdateForm
# from .forms import MsgForm
from django.http import HttpResponse
import socket
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .middleware import auth, guest
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
# from myapp.models import Profile  # Replace 'myapp' with your app name

# Create your views here.

def external(request):
    return HttpResponse('<h2>Django Chat App</h2> <iframe src="https://deadsimplechat.com/jZJO773Ni" width="100%" height="600px"></iframe>')

@auth
def home(request):

    # bind to the port with any IP address
    # port = 12345 
    # s = socket.socket(socket.AF_INET, socket.SOCK_STREAM) 
    # try:
    #     # Created Socket
    #     s = socket.socket(socket.AF_INET, socket.SOCK_STREAM) 
    #     # AF_INET: refers to the address-family ipv4 
    #     # SOCK_STREAM: Connection Oriented TCP Protocol
    # except socket.error as err:
    #             return render(request, 'error.html', {'error':err})
    # print('username', request.user.username)
    msgfrm = MsgForm()

    # print(s,s)
    # print('method', request.method)

    if request.method == 'POST':
        print('request.POST',request.POST)
        msgfrm = MsgForm(request.POST)
        print('msgfrm err', msgfrm.errors)
        if msgfrm.is_valid():
            print('msgfrm', msgfrm)
            msg_instance = msgfrm.save(commit=False)  # Don’t save to the database yet
            msg_instance.user = request.user  # Assign the logged-in user
            msg_instance.save()  # Save to the database

            # connect to the server on local computer  
            # s.connect(('127.0.0.1', port)) 

            # # Send data to the server
            # message = "Hello, Server!"
            # s.send(message.encode('utf-8'))

            # # receive data from the server and decoding to get the string.
            # response = s.recv(1024).decode('utf-8')
            # print ('rcv', response)
            # # close the connection 
            # s.close()   
            
            return render(request,'home.html',{'msgfrm':msgfrm})
    
    # s.bind(('127.0.0.1', port))

    # # socket listening
    # s.listen(5)

    # while True:
    #     c, addr = s.accept()
    #     print('Got connection from', addr )

    #     # Receive data from the client
    #     data = c.recv(1024).decode('utf-8')
    #     print(f"Received from client: {data}")

    #     # Send a response back to the client
    #     response = "Thank you for connecting"
    #     c.send(response.encode('utf-8'))
    #     # c.send(msgfrm.data.get('msg'))

    #     # Close the connection with the Client
    #     c.close()

    #     # Breaking once connection closed
    #     break
    
    msgs = list(Msg.objects.all())
    msg_dict = dict((i.user.username, [i.msg, i.senton, i.user.profile.image]) for i in msgs)

    # for k in msg_dict.keys():
    #     print(k, msg_dict[k][0])
    
    return render(request, 'home.html', {'msgfrm':msgfrm, 'msgs':msg_dict})

@auth 
def update(request):
    if request.method == 'POST':
        profile = ProfileUpdateForm(request.POST, request.FILES)
        if profile.is_valid():
            profile_inst = profile.save(commit=False)
            profile_inst.user = request.user
            profile_inst.save()
            return redirect('home')
    else:
        profile = ProfileUpdateForm()
        return render(request, 'update.html', {'profile_form':profile})

# def profile(request):
#     users_without_profile = User.objects.filter(profile__isnull=True)

#     for user in users_without_profile:
#         Profile.objects.create(user=user)

#     return redirect('home')




@guest
def userRegistration(request):
    if request.method=='POST':
        regForm = UserCreationForm(request.POST)
        if regForm.is_valid():
            user = regForm.save()
            login(request,user)
            request.session['username'] = user.username
            return redirect('home')
    else:
        initials = {'username':'', 'password1':'', 'password2':''}
        regForm = UserCreationForm(initial=initials)
    return render(request,'auth/registration.html', {'form':regForm})

@guest
def userLogin(request):
    if request.method=='POST':
        loginForm = AuthenticationForm(request, data=request.POST)    
        if loginForm.is_valid():
            user = loginForm.get_user()
            login(request, user)
            return redirect('home') 
    else: 
        initials = {'username':'', 'password':''}  # to prevent form from being empty when user revisits the page
        loginForm = AuthenticationForm(initial=initials)
    return render(request,'auth/login.html', {'form':loginForm})

def userLogout(request):
    logout(request)
    return redirect('login')

myproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <title>Material Design for Bootstrap</title>
        <!-- MDB icon -->
        <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
        <!-- Google Fonts Roboto -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />


        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
        
        <!-- MDB -->
        <link rel="stylesheet" href="{% static 'css/bootstrap-chat.min.css' %}">
    </head>

    {% block content %} {% endblock %} 

</html>

myproject/templates/error.html
<h2>{{ error }}</h2>

myproject/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block content %}

    <body>
        
        <!-- Start your project here-->
        <style>
            .gradient-custom {
            /* fallback for old browsers */
            background: #fccb90;

            /* Chrome 10-25, Safari 5.1-6 */
            background: -webkit-linear-gradient(to bottom right, rgba(252, 203, 144, 1), rgba(213, 126, 235, 1));

            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to bottom right, rgba(252, 203, 144, 1), rgba(213, 126, 235, 1))
            }

            .mask-custom {
            background: rgba(24, 24, 16, .2);
            border-radius: 2em;
            backdrop-filter: blur(15px);
            border: 2px solid rgba(255, 255, 255, 0.05);
            background-clip: padding-box;
            box-shadow: 10px 10px 10px rgba(46, 54, 68, 0.03);
            }
        </style>

        <section class="gradient-custom">
            <div class="container py-5 text-center">

            <div class="row">

               <div class="col-md-6 col-lg-5 col-xl-5 mb-4 mb-md-0">

                <h5 class="font-weight-bold mb-3 text-center text-white">
                {{ user.username }}

                </h5>

                <a class="text-end" href="{% url 'logout' %}">Logout</a>

                <div class="card mask-custom">
                    <div class="card-body">
                    <ul class="list-unstyled mb-0 msg-container">
                        {% for k,m in msgs.items %}
                        <li class="p-2 border-bottom" style="border-bottom: 1px solid rgba(255,255,255,.3) !important;">
                        <a href="javascript:void(0);" class="d-flex justify-content-between link-light">
                            <div class="d-flex flex-row">
                            <img src="{{ MEDIA_URL}}media/{{m.2}}" alt="avatar"
                                class="rounded-circle d-flex align-self-center me-3 shadow-1-strong" width="60">
                            <div class="pt-1">
                                <p class="fw-bold mb-0">
                                {{k}}
                                {% if k == user.username %} (me) {% endif %}
                                </p>
                                <p class="small text-white">{{m.0}}</p>
                            </div>
                            </div>
                            <div class="pt-1">
                            <p class="small text-white mb-1">{{m.1}}</p>
                            {% comment %} <span class="badge bg-danger float-end">1</span> {% endcomment %}
                            </div>
                        </a>
                        </li>
                        {% endfor %}
                    </ul> 

                    </div>
                </div> 

                </div> 

                <div class="col-md-6 col-lg-7 col-xl-7">

                

                <form method="POST" id="msgForm" action="">
                    {% csrf_token %}
                    <ul class="list-unstyled text-white" id="msg-container">  
                    </ul>

                    <div class="mb-3">
                        {% comment %} <div class="form-outline form-white" style="display:none;">
                            {{ msgfrm.user }}
                        </div>
                        {% for err in msgfrm.user.errors %}
                        <span class="text-danger">{{ err }}</span>
                        {% endfor %} {% endcomment %}
                        <div class="form-outline form-white"> 
                            {{ msgfrm.msg }}
                        </div>
                        {% for err in msgfrm.msg.errors %}
                        <span class="text-danger">{{ err }}</span>
                        {% endfor %}
                    </div>
                    <button type="button" class="btn btn-light btn-lg btn-rounded float-end btn-send" id="msgBtn">Send</button>

                </form>

                </div>

            </div>

            </div>
        </section>
        <!-- End your project here-->

        <!-- MDB -->
        <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
        <!-- Custom scripts -->
        <script type="text/javascript">

            var uname = '{{ user.username }}';  
            var img = '{{ MEDIA_URL }}media/{{ user.profile.image }}';  

            const chatSocket = new WebSocket("ws://" + window.location.host + "/");
            chatSocket.onopen = function(e) {
                console.log("The Connection was setup Successfully!");
            }

            chatSocket.close = function(e) {
                console.log("The Connection was got Lost!");
            }

            document.querySelector("#msgArea").focus();
            document.querySelector("#msgArea").onkeyup = function(e) {
                if(e.keyCode == 13) {
                    document.querySelector("#msgBtn").click();
                }
            }

            document.querySelector("#msgBtn").onclick = function(e) {
                var messageInput = document.querySelector("#msgArea").value;
                var currTime = new Date();
                var time = currTime.toLocaleTimeString();
                chatSocket.send(JSON.stringify({
                    message: messageInput,
                    username: uname,
                    time: time
                }));
            }

            chatSocket.onmessage = function(e) {
                const data = JSON.parse(e.data);
                console.log('data', data);

                var messageContainer = document.querySelector("#msg-container");
                var msgBox = document.createElement("li");
                var style = '';
                msgBox.className = "d-flex justify-content-between mb-6";
                if (data.username == uname) {
                    msgBox.className += " flex-row-reverse";
                    style = 'border-color: green;';
                }

                 

                var el = `<div class="card mask-custom" style="${style}">`+
                            `<div class="card-header d-flex justify-content-between p-3"`+
                            `style="border-bottom: 1px solid rgba(255,255,255,.3); width:200px;">`+
                            `<p class="fw-bold mb-0"> ${data.username} </p>`+
                            `<p class="text-light small mb-0"><i class="far fa-clock"></i> ${data.time} </p>`+
                            `</div>`+
                            `<div class="card-body">`+
                            `<p class="mb-0"> ${data.message}` +
                            `</p>`+
                            `</div>`+
                        `</div>`;
                
                    
                msgBox.innerHTML = el;

                document.querySelector("#msgArea").value = '';

                messageContainer.append(msgBox);

                // $("#msgForm").submit();
                
                $.ajax({
                    type:'POST',
                    url:'{% url "home" %}',
                    data:
                    {
                        user: data.username,
                        msg: data.message,
                        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                    },
                    success:function(){
                    //alert('Saved');
                    }
                })
            }

            //$(document).ready(function(event) {
            //   curr_id = '{{ user.id }}';
            //    console.log('curr_id',curr_id);
            //    $("#id_user option[value='"+curr_id+"']").attr('selected','selected') ;
            //});

        </script>
    </body>

{% endblock %}    

myproject/templates/update.html
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ profile_form.as_div }}
    <button type="submit" class="btn btn-dark">Upload</button>
</form> 